domain: ""

jxRequirements:
  cluster:
    gitKind: ""
    gitName: ""
    gitServer: ""

# empty values typically populated by external secrets
secrets:
  mavenSettings: ""
  mavenSecuritySettings: ""

  gitUsername: ""
  gitPassword: ""

  dockerConfigJSON: "{}"
