domain: ""

jxRequirements:
  cluster:
    gitKind: ""
    gitName: ""
    gitServer: ""

# enable being able to create PipelineActivity resources to replicate running pipelines to CRDs
role:
  pipelineActivity:
    enabled: true

serviceAccounts:
  # enable tekton RBAC for creating pipelines
  jenkins:
    name: jenkins
    rbac:
      cluster: true

  # enable tekton RBAC for creating pipelines
  agent:
    name: ""

  tektonBot:
    enabled: false
    name: tekton-bot
    rbac:
      cluster: true

# empty values typically populated by external secrets
secrets:
  mavenSettings: ""
  mavenSecuritySettings: ""

  gitUsername: ""
  gitPassword: ""

  dockerConfigJSON: "{}"
