apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-maven-settings
data:
  settings.xml: {{ .Values.secrets.mavenSettings| b64enc | quote }}
  settings-security.xml: {{ .Values.secrets.mavenSecuritySettings | b64enc | quote }}
