{{ if .Values.role.pipelineActivity.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-pipeline-activity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-pipeline-activity
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: {{ .Release.Namespace }}
{{- end }}