{{- if .Values.serviceAccounts.tektonBot.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ .Values.serviceAccounts.tektonBot.name | default "tekton-bot" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ .Values.serviceAccounts.tektonBot.name | default "tekton-bot" | quote }}
subjects:
- kind: ServiceAccount
  name:  {{ .Values.serviceAccounts.tektonBot.name | default "tekton-bot" | quote }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
