apiVersion: v1
data:
  password: {{ .Values.secrets.gitPassword | b64enc | quote }}
  username: {{ .Values.secrets.gitUsername | b64enc | quote }}
kind: Secret
metadata:
  name: tekton-git
  annotations:
    tekton.dev/git-0: {{ .Values.jxRequirements.cluster.gitServer | default "https://github.com" }}
    jenkins.io/credentials-description: API Token for acccessing {{ .Values.jxRequirements.cluster.gitServer | default "https://github.com" }}
      Git service inside pipelines
    jenkins.io/name: "jx-git-secret"
    jenkins.io/url: {{ .Values.jxRequirements.cluster.gitServer | default "https://github.com" }}
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
    jenkins.io/kind: git
    jenkins.io/service-kind: {{ .Values.jxRequirements.cluster.gitKind | default "github" }}
type: kubernetes.io/basic-auth
