{{- if .Values.serviceAccounts.tektonBot.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.tektonBot.name | default "tekton-bot" | quote }}
  {{- if .Values.pipeline.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.pipeline.serviceAccount.annotations | nindent 4 }}
  {{- end }}
secrets:
- name: tekton-container-registry-auth
- name: tekton-git
{{- end }}